[tool.poetry]
name = "first-neurons"
version = "0.1.0"
description = ""
authors = ["ochdev <contact@och.dev>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.19.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
